# Generated by Django 5.2.3 on 2025-06-14 15:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataProcessingActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("COLLECTION", "Συλλογή"),
                            ("STORAGE", "Αποθήκευση"),
                            ("PROCESSING", "Επεξεργασία"),
                            ("SHARING", "Κοινοποίηση"),
                            ("DELETION", "Διαγραφή"),
                            ("ANONYMIZATION", "Ανωνυμοποίηση"),
                            ("EXPORT", "Εξαγωγή"),
                        ],
                        max_length=20,
                        verbose_name="Τύπος δραστηριότητας",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("LEAVE_MANAGEMENT", "Διαχείριση αδειών"),
                            ("ADMINISTRATIVE", "Διοικητικοί σκοποί"),
                            ("LEGAL_COMPLIANCE", "Νομική συμμόρφωση"),
                            ("AUDIT", "Έλεγχος"),
                            ("REPORTING", "Αναφορές"),
                            ("SUPPORT", "Υποστήριξη"),
                        ],
                        max_length=20,
                        verbose_name="Σκοπός επεξεργασίας",
                    ),
                ),
                (
                    "data_categories",
                    models.TextField(verbose_name="Κατηγορίες δεδομένων"),
                ),
                ("description", models.TextField(verbose_name="Περιγραφή")),
                (
                    "legal_basis",
                    models.CharField(max_length=200, verbose_name="Νομική βάση"),
                ),
                (
                    "retention_period",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Περίοδος διατήρησης"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ημερομηνία"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Επιπλέον στοιχεία"
                    ),
                ),
            ],
            options={
                "verbose_name": "Δραστηριότητα Επεξεργασίας Δεδομένων",
                "verbose_name_plural": "Δραστηριότητες Επεξεργασίας Δεδομένων",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DataSubjectRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("ACCESS", "Δικαίωμα πρόσβασης (Άρθρο 15)"),
                            ("RECTIFICATION", "Δικαίωμα διόρθωσης (Άρθρο 16)"),
                            ("ERASURE", "Δικαίωμα διαγραφής (Άρθρο 17)"),
                            ("RESTRICTION", "Δικαίωμα περιορισμού (Άρθρο 18)"),
                            ("PORTABILITY", "Δικαίωμα φορητότητας (Άρθρο 20)"),
                            ("OBJECTION", "Δικαίωμα αντίρρησης (Άρθρο 21)"),
                        ],
                        max_length=20,
                        verbose_name="Τύπος αιτήματος",
                    ),
                ),
                ("description", models.TextField(verbose_name="Περιγραφή αιτήματος")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Εκκρεμεί"),
                            ("IN_PROGRESS", "Υπό επεξεργασία"),
                            ("COMPLETED", "Ολοκληρώθηκε"),
                            ("REJECTED", "Απορρίφθηκε"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Κατάσταση",
                    ),
                ),
                ("response", models.TextField(blank=True, verbose_name="Απάντηση")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Ημερομηνία αιτήματος"
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(verbose_name="Καταληκτική ημερομηνία"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ημερομηνία ολοκλήρωσης"
                    ),
                ),
            ],
            options={
                "verbose_name": "Αίτημα Υποκειμένου Δεδομένων",
                "verbose_name_plural": "Αιτήματα Υποκειμένων Δεδομένων",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        unique=True,
                        verbose_name="Κωδικός επαλήθευσης",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("APPLICATION", "Αίτηση άδειας"),
                            ("DECISION", "Απόφαση άδειας"),
                            ("PROTOCOL", "Έγγραφο με πρωτόκολλο"),
                            ("ATTACHMENT", "Συνημμένο"),
                        ],
                        max_length=20,
                        verbose_name="Τύπος εγγράφου",
                    ),
                ),
                (
                    "document_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Τίτλος εγγράφου"
                    ),
                ),
                (
                    "document_hash",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Hash εγγράφου"
                    ),
                ),
                (
                    "document_metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Metadata εγγράφου"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ενεργό")),
                (
                    "verified_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Φορές επαλήθευσης"
                    ),
                ),
                (
                    "last_verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Τελευταία επαλήθευση"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Δημιουργήθηκε"
                    ),
                ),
            ],
            options={
                "verbose_name": "Επαλήθευση Εγγράφου",
                "verbose_name_plural": "Επαληθεύσεις Εγγράφων",
            },
        ),
        migrations.CreateModel(
            name="GDPRConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("consent_text", models.TextField(verbose_name="Κείμενο συναίνεσης")),
                (
                    "consent_version",
                    models.CharField(max_length=20, verbose_name="Έκδοση συναίνεσης"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "consented_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Ημερομηνία συναίνεσης"
                    ),
                ),
            ],
            options={
                "verbose_name": "Συναίνεση GDPR",
                "verbose_name_plural": "Συναινέσεις GDPR",
                "ordering": ["-consented_at"],
            },
        ),
    ]
