# Generated by Django 5.2.3 on 2025-06-14 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("attachments_app", "0003_initial"),
        ("gdpr_app", "0001_initial"),
        ("leave_app", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataprocessingactivity",
            name="data_subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.employee",
                verbose_name="Υποκείμενο δεδομένων",
            ),
        ),
        migrations.AddField(
            model_name="dataprocessingactivity",
            name="processed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="data_processing_activities",
                to="users.employee",
                verbose_name="Επεξεργάστηκε από",
            ),
        ),
        migrations.AddField(
            model_name="datasubjectrequest",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_gdpr_requests",
                to="users.employee",
                verbose_name="Ανατέθηκε σε",
            ),
        ),
        migrations.AddField(
            model_name="datasubjectrequest",
            name="data_subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.employee",
                verbose_name="Υποκείμενο δεδομένων",
            ),
        ),
        migrations.AddField(
            model_name="documentverification",
            name="attachment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="attachments_app.leaveattachment",
                verbose_name="Συνημμένο",
            ),
        ),
        migrations.AddField(
            model_name="documentverification",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.employee",
                verbose_name="Δημιουργήθηκε από",
            ),
        ),
        migrations.AddField(
            model_name="documentverification",
            name="leave_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="leave_app.leaverequest",
                verbose_name="Αίτηση άδειας",
            ),
        ),
        migrations.AddField(
            model_name="gdprconsent",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.employee",
                verbose_name="Υπάλληλος",
            ),
        ),
        migrations.AddIndex(
            model_name="documentverification",
            index=models.Index(
                fields=["document_uuid"], name="gdpr_app_do_documen_ff58a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentverification",
            index=models.Index(
                fields=["leave_request"], name="gdpr_app_do_leave_r_77fca5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentverification",
            index=models.Index(
                fields=["document_type"], name="gdpr_app_do_documen_2fac10_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gdprconsent",
            index=models.Index(
                fields=["employee"], name="gdpr_app_gd_employe_20f7df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gdprconsent",
            index=models.Index(
                fields=["consented_at"], name="gdpr_app_gd_consent_4c4b07_idx"
            ),
        ),
    ]
