# Generated by Django 5.2.3 on 2025-06-14 07:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BloodDonationTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "donation_date",
                    models.DateField(verbose_name="Ημερομηνία αιμοδοσίας"),
                ),
                (
                    "was_successful",
                    models.BooleanField(null=True, verbose_name="Επιτυχής αιμοδοσία"),
                ),
                (
                    "hospital_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Νοσοκομείο"
                    ),
                ),
                (
                    "certificate_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Αρ. βεβαίωσης"
                    ),
                ),
                (
                    "additional_days_granted",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Επιπλέον ημέρες που χορηγήθηκαν"
                    ),
                ),
                (
                    "additional_days_used",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Επιπλέον ημέρες που χρησιμοποιήθηκαν"
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="Έτος")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Παρακολούθηση Αιμοδοσίας",
                "verbose_name_plural": "Παρακολούθηση Αιμοδοσιών",
            },
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_days",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Συνολικές ημέρες",
                    ),
                ),
                (
                    "working_days",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Εργάσιμες ημέρες"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Για προφορικές/εορταστικές άδειες",
                        verbose_name="Περιγραφή",
                    ),
                ),
                (
                    "is_self_declaration",
                    models.BooleanField(
                        default=False, verbose_name="Με υπεύθυνη δήλωση"
                    ),
                ),
                (
                    "comments_to_leave_department",
                    models.TextField(
                        blank=True, verbose_name="Σχόλια προς τμήμα αδειών"
                    ),
                ),
                (
                    "kedasy_protocol_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Αρ. Πρωτοκόλλου ΚΕΔΑΣΥ/ΚΕΠΕΑ",
                    ),
                ),
                (
                    "kedasy_protocol_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Ημερομηνία πρωτοκόλλου ΚΕΔΑΣΥ/ΚΕΠΕΑ",
                    ),
                ),
                (
                    "pdede_protocol_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Αρ. Πρωτ. ΠΔΕΔΕ"
                    ),
                ),
                (
                    "pdede_protocol_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Ημερομηνία πρωτοκόλλου ΠΔΕΔΕ",
                    ),
                ),
                (
                    "manager_approved_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Ημερομηνία έγκρισης προϊσταμένου",
                    ),
                ),
                (
                    "manager_rejection_reason",
                    models.TextField(
                        blank=True, verbose_name="Λόγος μη έγκρισης από προϊστάμενο"
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ημερομηνία επεξεργασίας"
                    ),
                ),
                (
                    "processing_notes",
                    models.TextField(
                        blank=True, verbose_name="Σημειώσεις επεξεργασίας"
                    ),
                ),
                (
                    "leave_dept_rejection_reason",
                    models.TextField(
                        blank=True, verbose_name="Λόγοι απόρριψης από τμήμα αδειών"
                    ),
                ),
                (
                    "required_documents",
                    models.TextField(
                        blank=True, verbose_name="Απαιτούμενα δικαιολογητικά"
                    ),
                ),
                (
                    "health_committee_decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "---"),
                            ("Εγκρίθηκε", "Εγκρίθηκε"),
                            ("Απορρίφθηκε", "Απορρίφθηκε"),
                        ],
                        max_length=50,
                        verbose_name="Απόφαση υγειονομικής επιτροπής",
                    ),
                ),
                (
                    "health_committee_notes",
                    models.TextField(
                        blank=True, verbose_name="Σημειώσεις υγειονομικής επιτροπής"
                    ),
                ),
                (
                    "health_committee_decided_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Ημερομηνία απόφασης επιτροπής",
                    ),
                ),
                (
                    "is_cancellation",
                    models.BooleanField(default=False, verbose_name="Είναι ανάκληση"),
                ),
                (
                    "is_partial_cancellation",
                    models.BooleanField(
                        default=False, verbose_name="Είναι μερική ανάκληση"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Δημιουργήθηκε"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ενημερώθηκε"),
                ),
            ],
            options={
                "verbose_name": "Αίτηση Άδειας",
                "verbose_name_plural": "Αιτήσεις Αδειών",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeaveRequestPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Από")),
                ("end_date", models.DateField(verbose_name="Έως")),
                (
                    "total_days",
                    models.PositiveIntegerField(verbose_name="Συνολικές ημέρες"),
                ),
                (
                    "working_days",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Εργάσιμες ημέρες"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Διάστημα Άδειας",
                "verbose_name_plural": "Διαστήματα Αδειών",
            },
        ),
        migrations.CreateModel(
            name="LeaveStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Όνομα κατάστασης"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Περιγραφή")),
                (
                    "color_code",
                    models.CharField(
                        default="#CCCCCC", max_length=7, verbose_name="Χρώμα (HEX)"
                    ),
                ),
                (
                    "is_final_status",
                    models.BooleanField(default=False, verbose_name="Τελική κατάσταση"),
                ),
                (
                    "order_priority",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Σειρά προτεραιότητας"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ενεργή")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Κατάσταση Άδειας",
                "verbose_name_plural": "Καταστάσεις Αδειών",
                "ordering": ["order_priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_adeias",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="ID άδειας"
                    ),
                ),
                (
                    "eidos_adeias",
                    models.CharField(max_length=200, verbose_name="Είδος άδειας"),
                ),
                (
                    "eidos_adeias_aplo",
                    models.CharField(max_length=100, verbose_name="Είδος άδειας απλό"),
                ),
                (
                    "keimeno_thematos_adeia",
                    models.TextField(verbose_name="Κείμενο θέματος άδειας"),
                ),
                (
                    "keimeno_apofasis_adeia",
                    models.TextField(verbose_name="Κείμενο απόφασης άδειας"),
                ),
                (
                    "thematikos_fakelos",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Θεματικός φάκελος"
                    ),
                ),
                (
                    "requires_manager_approval",
                    models.BooleanField(
                        default=True, verbose_name="Απαιτεί έγκριση προϊσταμένου"
                    ),
                ),
                (
                    "requires_attachments",
                    models.BooleanField(
                        default=False, verbose_name="Απαιτεί συνημμένα"
                    ),
                ),
                (
                    "requires_protocol",
                    models.BooleanField(
                        default=True, verbose_name="Απαιτεί πρωτόκολλο"
                    ),
                ),
                (
                    "requires_decision_pdf",
                    models.BooleanField(
                        default=True, verbose_name="Απαιτεί PDF απόφασης"
                    ),
                ),
                (
                    "bypass_manager_for_sick_leave",
                    models.BooleanField(
                        default=False,
                        verbose_name="Παράκαμψη προϊσταμένου για αναρρωτικές",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Ενεργός"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Τύπος Άδειας",
                "verbose_name_plural": "Τύποι Αδειών",
                "ordering": ["eidos_adeias"],
            },
        ),
    ]
