# Generated by Django 5.2.3 on 2025-06-14 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("leave_app", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blooddonationtracking",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.employee",
                verbose_name="Υπάλληλος",
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_leave_requests",
                to="users.employee",
                verbose_name="Δημιουργήθηκε από",
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.employee",
                verbose_name="Υπάλληλος",
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="manager_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_leave_requests",
                to="users.employee",
                verbose_name="Εγκρίθηκε από προϊστάμενο",
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="parent_leave",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="leave_app.leaverequest",
                verbose_name="Γονική άδεια",
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_leave_requests",
                to="users.employee",
                verbose_name="Επεξεργάστηκε από",
            ),
        ),
        migrations.AddField(
            model_name="blooddonationtracking",
            name="leave_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="leave_app.leaverequest",
                verbose_name="Αίτηση άδειας",
            ),
        ),
        migrations.AddField(
            model_name="leaverequestperiod",
            name="leave_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="periods",
                to="leave_app.leaverequest",
                verbose_name="Αίτηση άδειας",
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="leave_app.leavestatus",
                verbose_name="Κατάσταση",
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="leave_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="leave_app.leavetype",
                verbose_name="Τύπος άδειας",
            ),
        ),
        migrations.AddIndex(
            model_name="blooddonationtracking",
            index=models.Index(
                fields=["employee"], name="leave_app_b_employe_5e8f5a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blooddonationtracking",
            index=models.Index(fields=["year"], name="leave_app_b_year_3fd975_idx"),
        ),
        migrations.AddIndex(
            model_name="leaverequestperiod",
            index=models.Index(
                fields=["leave_request"], name="leave_app_l_leave_r_7750af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaverequestperiod",
            index=models.Index(
                fields=["start_date", "end_date"], name="leave_app_l_start_d_3971b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["employee"], name="leave_app_l_employe_06087f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["status"], name="leave_app_l_status__615281_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["created_at"], name="leave_app_l_created_f9218f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["leave_type"], name="leave_app_l_leave_t_e8efe4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["employee", "status"], name="leave_app_l_employe_4324aa_idx"
            ),
        ),
    ]
