# Generated by Django 5.2.3 on 2025-06-14 11:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={
                "verbose_name": "Υπάλληλος αδειών",
                "verbose_name_plural": "Υπάλληλοι αδειών",
            },
        ),
    ]
