# Generated by Django 5.2.3 on 2025-06-14 11:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_employee_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "verbose_name": "Υποψήφιος Χρήστης",
                "verbose_name_plural": "Υποψήφιοι Χρήστες",
            },
        ),
        migrations.AlterModelOptions(
            name="employee",
            options={
                "verbose_name": "Πιστοποιημένος Χρήστης",
                "verbose_name_plural": "Πιστοποιημένοι Χρήστες",
            },
        ),
    ]
