# Generated by Django 5.2.3 on 2025-06-14 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attachments_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataRetentionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("ARCHIVE", "Αρχειοθέτηση"),
                            ("DELETE", "Διαγραφή"),
                            ("ANONYMIZE", "Ανωνυμοποίηση"),
                            ("EXPORT", "Εξαγωγή"),
                        ],
                        max_length=10,
                        verbose_name="Ενέργεια",
                    ),
                ),
                (
                    "object_type",
                    models.CharField(max_length=50, verbose_name="Τύπος αντικειμένου"),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(verbose_name="ID αντικειμένου"),
                ),
                (
                    "object_description",
                    models.TextField(verbose_name="Περιγραφή αντικειμένου"),
                ),
                ("reason", models.TextField(verbose_name="Λόγος")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ημερομηνία"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
            ],
            options={
                "verbose_name": "Log Διατήρησης Δεδομένων",
                "verbose_name_plural": "Logs Διατήρησης Δεδομένων",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        choices=[
                            ("specialty", "Ειδικότητα"),
                            ("employee_type", "Τύπος υπαλλήλου"),
                            ("current_service", "Υπηρεσία"),
                            ("department", "Τμήμα"),
                            ("role_description", "Περιγραφή ρόλου"),
                            ("regular_leave_days", "Ημέρες κανονικής άδειας"),
                            ("carryover_leave_days", "Μεταφερόμενες ημέρες"),
                            (
                                "self_declaration_sick_days_remaining",
                                "Υπόλοιπο ημερών με υπ. δήλωση",
                            ),
                            ("is_active", "Ενεργότητα"),
                            ("can_request_leave", "Δικαίωμα αίτησης άδειας"),
                            ("personal_email", "Προσωπικό email"),
                            ("phone1", "Τηλέφωνο 1"),
                            ("phone2", "Τηλέφωνο 2"),
                            ("schedule", "Ωράριο"),
                        ],
                        max_length=50,
                        verbose_name="Πεδίο",
                    ),
                ),
                (
                    "previous_value",
                    models.TextField(blank=True, verbose_name="Προηγούμενη τιμή"),
                ),
                ("new_value", models.TextField(blank=True, verbose_name="Νέα τιμή")),
                (
                    "change_reason",
                    models.TextField(blank=True, verbose_name="Λόγος αλλαγής"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Ημερομηνία αλλαγής"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ιστορικό Υπαλλήλου",
                "verbose_name_plural": "Ιστορικά Υπαλλήλων",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeaveActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Δημιουργία"),
                            ("STATUS_CHANGE", "Αλλαγή κατάστασης"),
                            ("APPROVAL", "Έγκριση"),
                            ("REJECTION", "Απόρριψη"),
                            ("CANCELLATION", "Ανάκληση"),
                            ("EDIT", "Επεξεργασία"),
                            ("VIEW", "Προβολή"),
                            ("DOWNLOAD", "Λήψη"),
                            ("ATTACHMENT_ADD", "Προσθήκη συνημμένου"),
                            ("ATTACHMENT_DELETE", "Διαγραφή συνημμένου"),
                            ("PROTOCOL_ADD", "Προσθήκη πρωτοκόλλου"),
                            ("HEALTH_COMMITTEE", "Υγειονομική επιτροπή"),
                        ],
                        max_length=20,
                        verbose_name="Ενέργεια",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Σημειώσεις")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ημερομηνία"),
                ),
            ],
            options={
                "verbose_name": "Log Ενέργειας Άδειας",
                "verbose_name_plural": "Logs Ενεργειών Αδειών",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "Debug"),
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=10,
                        verbose_name="Επίπεδο",
                    ),
                ),
                ("message", models.TextField(verbose_name="Μήνυμα")),
                (
                    "module",
                    models.CharField(blank=True, max_length=100, verbose_name="Module"),
                ),
                (
                    "function_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Function"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Επιπλέον δεδομένα"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ημερομηνία"),
                ),
            ],
            options={
                "verbose_name": "Log Συστήματος",
                "verbose_name_plural": "Logs Συστήματος",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("VIEW", "Προβολή"),
                            ("DOWNLOAD", "Λήψη"),
                            ("EDIT", "Επεξεργασία"),
                            ("DELETE", "Διαγραφή"),
                            ("EXPORT", "Εξαγωγή"),
                            ("PRINT", "Εκτύπωση"),
                        ],
                        max_length=10,
                        verbose_name="Τύπος πρόσβασης",
                    ),
                ),
                (
                    "url_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="URL Path"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Ημερομηνία πρόσβασης"
                    ),
                ),
                (
                    "attachment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="attachments_app.leaveattachment",
                        verbose_name="Συνημμένο",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log Πρόσβασης",
                "verbose_name_plural": "Logs Πρόσβασης",
                "ordering": ["-created_at"],
            },
        ),
    ]
