# Generated by Django 5.2.3 on 2025-06-14 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("audit_app", "0001_initial"),
        ("leave_app", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesslog",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.employee",
                verbose_name="Χρήστης που έκανε πρόσβαση",
            ),
        ),
        migrations.AddField(
            model_name="accesslog",
            name="leave_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="leave_app.leaverequest",
                verbose_name="Αίτηση άδειας",
            ),
        ),
        migrations.AddField(
            model_name="accesslog",
            name="viewed_employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_logs_viewed",
                to="users.employee",
                verbose_name="Υπάλληλος που προβλήθηκε",
            ),
        ),
        migrations.AddField(
            model_name="dataretentionlog",
            name="performed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.employee",
                verbose_name="Εκτελέστηκε από",
            ),
        ),
        migrations.AddField(
            model_name="employeehistory",
            name="changed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employee_changes_made",
                to="users.employee",
                verbose_name="Άλλαξε από",
            ),
        ),
        migrations.AddField(
            model_name="employeehistory",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.employee",
                verbose_name="Υπάλληλος",
            ),
        ),
        migrations.AddField(
            model_name="leaveactionlog",
            name="leave_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="leave_app.leaverequest",
                verbose_name="Αίτηση άδειας",
            ),
        ),
        migrations.AddField(
            model_name="leaveactionlog",
            name="new_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="new_status_logs",
                to="leave_app.leavestatus",
                verbose_name="Νέα κατάσταση",
            ),
        ),
        migrations.AddField(
            model_name="leaveactionlog",
            name="previous_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="previous_status_logs",
                to="leave_app.leavestatus",
                verbose_name="Προηγούμενη κατάσταση",
            ),
        ),
        migrations.AddField(
            model_name="leaveactionlog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.employee",
                verbose_name="Χρήστης",
            ),
        ),
        migrations.AddField(
            model_name="systemlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.employee",
                verbose_name="Χρήστης",
            ),
        ),
        migrations.AddIndex(
            model_name="accesslog",
            index=models.Index(
                fields=["employee"], name="audit_app_a_employe_a81c1e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accesslog",
            index=models.Index(
                fields=["viewed_employee"], name="audit_app_a_viewed__da9a47_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accesslog",
            index=models.Index(
                fields=["created_at"], name="audit_app_a_created_762c19_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accesslog",
            index=models.Index(
                fields=["access_type"], name="audit_app_a_access__fd15e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeehistory",
            index=models.Index(
                fields=["employee"], name="audit_app_e_employe_a686d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeehistory",
            index=models.Index(
                fields=["field_name"], name="audit_app_e_field_n_af3a42_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeehistory",
            index=models.Index(
                fields=["created_at"], name="audit_app_e_created_9a1885_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaveactionlog",
            index=models.Index(
                fields=["leave_request"], name="audit_app_l_leave_r_f08f3a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaveactionlog",
            index=models.Index(fields=["user"], name="audit_app_l_user_id_67e80d_idx"),
        ),
        migrations.AddIndex(
            model_name="leaveactionlog",
            index=models.Index(
                fields=["created_at"], name="audit_app_l_created_9a47a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaveactionlog",
            index=models.Index(fields=["action"], name="audit_app_l_action_5c8f9a_idx"),
        ),
        migrations.AddIndex(
            model_name="systemlog",
            index=models.Index(fields=["level"], name="audit_app_s_level_5a4058_idx"),
        ),
        migrations.AddIndex(
            model_name="systemlog",
            index=models.Index(
                fields=["created_at"], name="audit_app_s_created_27ea60_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="systemlog",
            index=models.Index(fields=["user"], name="audit_app_s_user_id_cd851c_idx"),
        ),
    ]
