# Generated by Django 5.2.3 on 2025-06-14 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attachments_app", "0001_initial"),
        ("leave_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaveattachment",
            name="leave_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="leave_app.leaverequest",
                verbose_name="Αίτηση άδειας",
            ),
        ),
    ]
