# Generated by Django 5.2.3 on 2025-06-14 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("attachments_app", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaveattachment",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="users.employee",
                verbose_name="Ανέβασε",
            ),
        ),
        migrations.AddIndex(
            model_name="leaveattachment",
            index=models.Index(
                fields=["leave_request"], name="attachments_leave_r_cb888c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaveattachment",
            index=models.Index(
                fields=["attachment_type"], name="attachments_attachm_3ab291_idx"
            ),
        ),
    ]
