# Generated by Django 5.2.3 on 2025-06-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HolidayOverlapCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Ημερομηνία")),
                (
                    "holiday_count",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Αριθμός αργιών"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Τελευταία ενημέρωση"
                    ),
                ),
            ],
            options={
                "verbose_name": "Έλεγχος Επικαλύψεων Αργιών",
                "verbose_name_plural": "Έλεγχοι Επικαλύψεων Αργιών",
            },
        ),
        migrations.CreateModel(
            name="PublicHoliday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Όνομα αργίας")),
                ("date", models.DateField(verbose_name="Ημερομηνία")),
                ("year", models.PositiveIntegerField(verbose_name="Έτος")),
                (
                    "is_fixed",
                    models.BooleanField(default=True, verbose_name="Σταθερή αργία"),
                ),
                (
                    "is_national",
                    models.BooleanField(default=True, verbose_name="Εθνική αργία"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ενεργή")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Δημόσια Αργία",
                "verbose_name_plural": "Δημόσιες Αργίες",
            },
        ),
    ]
