# Generated by Django 5.2.3 on 2025-06-14 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("calendar_app", "0001_initial"),
        ("core_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="holidayoverlapcheck",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core_app.city",
                verbose_name="Πόλη",
            ),
        ),
        migrations.AddField(
            model_name="publicholiday",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core_app.city",
                verbose_name="Πόλη (για τοπικές αργίες)",
            ),
        ),
    ]
