# Generated by Django 5.2.3 on 2025-06-14 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("calendar_app", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicholiday",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.employee",
                verbose_name="Δημιουργήθηκε από",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="holidayoverlapcheck",
            unique_together={("date", "city")},
        ),
        migrations.AddIndex(
            model_name="publicholiday",
            index=models.Index(fields=["date"], name="calendar_ap_date_ed4d92_idx"),
        ),
        migrations.AddIndex(
            model_name="publicholiday",
            index=models.Index(fields=["year"], name="calendar_ap_year_4219a2_idx"),
        ),
        migrations.AddIndex(
            model_name="publicholiday",
            index=models.Index(
                fields=["is_national"], name="calendar_ap_is_nati_c862cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publicholiday",
            index=models.Index(fields=["city"], name="calendar_ap_city_id_480d6d_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="publicholiday",
            unique_together={("date", "city")},
        ),
    ]
