# Generated by Django 5.2.3 on 2025-06-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Όνομα widget")),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("STAT_CARD", "Κάρτα στατιστικού"),
                            ("CHART", "Γράφημα"),
                            ("TABLE", "Πίνακας"),
                            ("CALENDAR", "Ημερολόγιο"),
                            ("LIST", "Λίστα"),
                        ],
                        max_length=20,
                        verbose_name="Τύπος widget",
                    ),
                ),
                (
                    "data_source",
                    models.CharField(max_length=100, verbose_name="Πηγή δεδομένων"),
                ),
                (
                    "configuration",
                    models.JSONField(default=dict, verbose_name="Διαμόρφωση"),
                ),
                (
                    "position_x",
                    models.PositiveIntegerField(default=0, verbose_name="Θέση X"),
                ),
                (
                    "position_y",
                    models.PositiveIntegerField(default=0, verbose_name="Θέση Y"),
                ),
                (
                    "width",
                    models.PositiveIntegerField(default=4, verbose_name="Πλάτος"),
                ),
                ("height", models.PositiveIntegerField(default=3, verbose_name="Ύψος")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ενεργό")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Dashboard Widget",
                "verbose_name_plural": "Dashboard Widgets",
                "ordering": ["position_y", "position_x"],
            },
        ),
        migrations.CreateModel(
            name="ReportExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(default=dict, verbose_name="Παράμετροι εκτέλεσης"),
                ),
                (
                    "output_format",
                    models.CharField(
                        choices=[
                            ("PDF", "PDF"),
                            ("EXCEL", "Excel"),
                            ("CSV", "CSV"),
                            ("HTML", "HTML"),
                        ],
                        default="PDF",
                        max_length=10,
                        verbose_name="Μορφή εξαγωγής",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Εκκρεμεί"),
                            ("RUNNING", "Εκτελείται"),
                            ("COMPLETED", "Ολοκληρώθηκε"),
                            ("FAILED", "Απέτυχε"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="Κατάσταση",
                    ),
                ),
                (
                    "progress",
                    models.PositiveIntegerField(default=0, verbose_name="Πρόοδος (%)"),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Διαδρομή αρχείου"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Μέγεθος αρχείου"
                    ),
                ),
                (
                    "row_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Αριθμός γραμμών"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ξεκίνησε στις"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ολοκληρώθηκε στις"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Μήνυμα σφάλματος"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Δημιουργήθηκε"
                    ),
                ),
            ],
            options={
                "verbose_name": "Εκτέλεση Αναφοράς",
                "verbose_name_plural": "Εκτελέσεις Αναφορών",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Όνομα προτύπου"),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("LEAVE_SUMMARY", "Περίληψη αδειών"),
                            ("EMPLOYEE_LEAVE_BALANCE", "Υπόλοιπα αδειών υπαλλήλων"),
                            ("DEPARTMENT_STATISTICS", "Στατιστικά τμήματος"),
                            ("MONTHLY_REPORT", "Μηνιαία αναφορά"),
                            ("ANNUAL_REPORT", "Ετήσια αναφορά"),
                            ("LEAVE_CALENDAR", "Ημερολόγιο αδειών"),
                            ("ATTENDANCE_REPORT", "Αναφορά παρουσιολογίου"),
                            ("PENDING_APPROVALS", "Εκκρεμείς εγκρίσεις"),
                        ],
                        max_length=30,
                        verbose_name="Τύπος αναφοράς",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Περιγραφή")),
                (
                    "parameters",
                    models.JSONField(default=dict, verbose_name="Παράμετροι"),
                ),
                ("columns", models.JSONField(default=list, verbose_name="Στήλες")),
                ("filters", models.JSONField(default=dict, verbose_name="Φίλτρα")),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="Δημόσια"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ενεργό")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Πρότυπο Αναφοράς",
                "verbose_name_plural": "Πρότυπα Αναφορών",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ScheduledReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Όνομα προγραμματισμού"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Καθημερινά"),
                            ("WEEKLY", "Εβδομαδιαία"),
                            ("MONTHLY", "Μηνιαία"),
                            ("QUARTERLY", "Τριμηνιαία"),
                            ("YEARLY", "Ετήσια"),
                        ],
                        max_length=10,
                        verbose_name="Συχνότητα",
                    ),
                ),
                (
                    "day_of_week",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="0=Δευτέρα, 6=Κυριακή",
                        null=True,
                        verbose_name="Ημέρα εβδομάδας",
                    ),
                ),
                (
                    "day_of_month",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Ημέρα μήνα"
                    ),
                ),
                (
                    "hour",
                    models.PositiveIntegerField(
                        default=8, verbose_name="Ώρα εκτέλεσης"
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(default=dict, verbose_name="Παράμετροι"),
                ),
                (
                    "output_format",
                    models.CharField(
                        choices=[
                            ("PDF", "PDF"),
                            ("EXCEL", "Excel"),
                            ("CSV", "CSV"),
                            ("HTML", "HTML"),
                        ],
                        default="PDF",
                        max_length=10,
                        verbose_name="Μορφή εξαγωγής",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Ενεργός"),
                ),
                (
                    "last_run",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Τελευταία εκτέλεση"
                    ),
                ),
                (
                    "next_run",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Επόμενη εκτέλεση"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Προγραμματισμένη Αναφορά",
                "verbose_name_plural": "Προγραμματισμένες Αναφορές",
            },
        ),
    ]
