# Generated by Django 5.2.3 on 2025-06-14 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("reports_app", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboardwidget",
            name="allowed_roles",
            field=models.ManyToManyField(
                blank=True, to="users.role", verbose_name="Επιτρεπόμενοι ρόλοι"
            ),
        ),
        migrations.AddField(
            model_name="reportexecution",
            name="executed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.employee",
                verbose_name="Εκτελέστηκε από",
            ),
        ),
        migrations.AddField(
            model_name="reporttemplate",
            name="allowed_roles",
            field=models.ManyToManyField(
                blank=True, to="users.role", verbose_name="Επιτρεπόμενοι ρόλοι"
            ),
        ),
        migrations.AddField(
            model_name="reporttemplate",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.employee",
                verbose_name="Δημιουργήθηκε από",
            ),
        ),
        migrations.AddField(
            model_name="reportexecution",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="reports_app.reporttemplate",
                verbose_name="Πρότυπο",
            ),
        ),
        migrations.AddField(
            model_name="scheduledreport",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_scheduled_reports",
                to="users.employee",
                verbose_name="Δημιουργήθηκε από",
            ),
        ),
        migrations.AddField(
            model_name="scheduledreport",
            name="recipients",
            field=models.ManyToManyField(
                related_name="scheduled_reports_as_recipient",
                to="users.employee",
                verbose_name="Παραλήπτες",
            ),
        ),
        migrations.AddField(
            model_name="scheduledreport",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="reports_app.reporttemplate",
                verbose_name="Πρότυπο αναφοράς",
            ),
        ),
    ]
