# Generated by Django 5.2.3 on 2025-06-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Όνομα πόλης"
                    ),
                ),
                (
                    "prefecture",
                    models.CharField(blank=True, max_length=100, verbose_name="Νομός"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ενεργή")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Πόλη",
                "verbose_name_plural": "Πόλεις",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Όνομα τμήματος"),
                ),
                (
                    "is_virtual",
                    models.BooleanField(
                        default=False, verbose_name="Εικονικό τμήμα (ΣΔΕΥ)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ενεργό")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Τμήμα",
                "verbose_name_plural": "Τμήματα",
            },
        ),
        migrations.CreateModel(
            name="EmployeeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Όνομα τύπου"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Περιγραφή")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Ενεργός"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Τύπος Υπαλλήλου",
                "verbose_name_plural": "Τύποι Υπαλλήλων",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Όνομα υπηρεσίας"),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Πλήρης ονομασία"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ενεργή")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Υπηρεσία",
                "verbose_name_plural": "Υπηρεσίες",
                "ordering": ["service_type__level", "name"],
            },
        ),
        migrations.CreateModel(
            name="ServiceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Όνομα τύπου"
                    ),
                ),
                (
                    "abbreviation",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Συντομογραφία"
                    ),
                ),
                (
                    "level",
                    models.PositiveIntegerField(
                        choices=[(1, "ΠΔΕΔΕ"), (2, "ΚΕΔΑΣΥ/ΚΕΠΕΑ"), (3, "ΣΔΕΥ")],
                        verbose_name="Επίπεδο ιεραρχίας",
                    ),
                ),
                (
                    "requires_kedasy_protocol",
                    models.BooleanField(
                        default=False, verbose_name="Απαιτεί πρωτόκολλο ΚΕΔΑΣΥ"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Ενεργός"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Τύπος Υπηρεσίας",
                "verbose_name_plural": "Τύποι Υπηρεσιών",
                "ordering": ["level", "name"],
            },
        ),
        migrations.CreateModel(
            name="Specialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specialty_full",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Πλήρης ειδικότητα"
                    ),
                ),
                (
                    "specialty_short",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Σύντομη ειδικότητα"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ενεργή")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Ειδικότητα",
                "verbose_name_plural": "Ειδικότητες",
                "ordering": ["specialty_short"],
            },
        ),
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Κλειδί"
                    ),
                ),
                ("value", models.TextField(verbose_name="Τιμή")),
                ("description", models.TextField(blank=True, verbose_name="Περιγραφή")),
                (
                    "is_system",
                    models.BooleanField(
                        default=False, verbose_name="Ρύθμιση συστήματος"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Ρύθμιση Συστήματος",
                "verbose_name_plural": "Ρυθμίσεις Συστήματος",
            },
        ),
    ]
