# Generated by Django 5.2.3 on 2025-06-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=500, verbose_name="Θέμα")),
                ("body", models.TextField(verbose_name="Κείμενο")),
                (
                    "to_email",
                    models.EmailField(max_length=254, verbose_name="Προς email"),
                ),
                ("cc_emails", models.TextField(blank=True, verbose_name="CC emails")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Εκκρεμεί"),
                            ("SENT", "Στάλθηκε"),
                            ("FAILED", "Απέτυχε"),
                            ("RETRYING", "Επανάληψη"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="Κατάσταση",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Στάλθηκε στις"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Μήνυμα σφάλματος"),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Αριθμός επαναλήψεων"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Δημιουργήθηκε"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ειδοποίηση Email",
                "verbose_name_plural": "Ειδοποιήσεις Email",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InAppNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Τίτλος")),
                ("message", models.TextField(verbose_name="Μήνυμα")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Χαμηλή"),
                            ("NORMAL", "Κανονική"),
                            ("HIGH", "Υψηλή"),
                            ("URGENT", "Επείγουσα"),
                        ],
                        default="NORMAL",
                        max_length=10,
                        verbose_name="Προτεραιότητα",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="Διαβάστηκε"),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Διαβάστηκε στις"
                    ),
                ),
                (
                    "action_url",
                    models.URLField(blank=True, verbose_name="URL ενέργειας"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Δημιουργήθηκε"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Λήγει στις"
                    ),
                ),
            ],
            options={
                "verbose_name": "In-App Ειδοποίηση",
                "verbose_name_plural": "In-App Ειδοποιήσεις",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("LEAVE_SUBMITTED", "Υποβολή αίτησης άδειας"),
                            ("LEAVE_APPROVED", "Έγκριση άδειας"),
                            ("LEAVE_REJECTED", "Απόρριψη άδειας"),
                            ("LEAVE_NEEDS_APPROVAL", "Άδεια προς έγκριση"),
                            ("LEAVE_DOCUMENTS_NEEDED", "Απαιτούνται δικαιολογητικά"),
                            ("LEAVE_COMPLETED", "Ολοκλήρωση άδειας"),
                            ("LEAVE_CANCELLED", "Ανάκληση άδειας"),
                        ],
                        max_length=30,
                        verbose_name="Τύπος ειδοποίησης",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="Ενεργή"),
                ),
                (
                    "email_enabled",
                    models.BooleanField(default=True, verbose_name="Email ενεργό"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Προτίμηση Ειδοποίησης",
                "verbose_name_plural": "Προτιμήσεις Ειδοποιήσεων",
            },
        ),
    ]
