# Generated by Django 5.2.3 on 2025-06-14 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("leave_app", "0002_initial"),
        ("notifications_app", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailnotification",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.employee",
                verbose_name="Παραλήπτης",
            ),
        ),
        migrations.AddField(
            model_name="emailnotification",
            name="leave_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="leave_app.leaverequest",
                verbose_name="Αίτηση άδειας",
            ),
        ),
        migrations.AddField(
            model_name="inappnotification",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.employee",
                verbose_name="Παραλήπτης",
            ),
        ),
        migrations.AddField(
            model_name="inappnotification",
            name="leave_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="leave_app.leaverequest",
                verbose_name="Αίτηση άδειας",
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.employee",
                verbose_name="Υπάλληλος",
            ),
        ),
        migrations.AddIndex(
            model_name="emailnotification",
            index=models.Index(fields=["status"], name="notificatio_status_b025c9_idx"),
        ),
        migrations.AddIndex(
            model_name="emailnotification",
            index=models.Index(
                fields=["employee"], name="notificatio_employe_d873d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailnotification",
            index=models.Index(
                fields=["created_at"], name="notificatio_created_46d929_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="notificationpreference",
            unique_together={("employee", "notification_type")},
        ),
    ]
